# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_login_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteuser',
            name='remote_username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
